version: '2'
services:
    wearplus-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/wearplus/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=wearplus
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
